### ISSUE TITLE
Bug: in add_action

### ISSUE THREAD

**Issue by bwsolutions** [eighty20results/import-users-from-csv#1]
I think you may have an typo in line 214.

`add_action( 'pmp_im_pre_user_import', array( self::get_instance(), 'pre_member_import' ) , 10, 2);`

It looks like the action is actually "pmp_im_pre_member_import".  So It does not look like pre_member_import is getting called.

**Comment by eighty20results** [comment]
Thanks for the report. Working on an update to the plugin now. Will push it upstream ASAP

**Comment by eighty20results** [comment]
Fixed in version 2.4, now available in the WordPress.org Plugin repository.
